spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangd6995@gmail.com
    password: xtzdmxdqdlhwljgg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분